### ISSUE TITLE
form__title has margin-bottom 2rem and v2-title has margin: 0 so ordering matters

### ISSUE THREAD

**Issue by jameslnewell** [nib-styles/react-form#1]
Mixin v2-title so we can control the order?

Or

Have a `@nib-styles/global` component that contains `* {margin: 0; padding: 0}`?

**Comment by lauriejones** [comment]
Which do you recommend? How would the global repo fix this?

**Comment by jameslnewell** [comment]
looks like we decided to use a mixin
