### ISSUE TITLE
Cannot find @nib-styles/v2-buttons/compiled

### ISSUE THREAD

**Issue by eastwood** [nib-styles/react-form#4]
When pulling down react form and compiling in tradie, the `v2-buttons` dependency is not found.
I'm assuming that the import `@nib-styles/v2-buttons/compiled` has been deprecated for `@nib-styles/v2-buttons` instead?

Can create PR to fix :)

**Comment by lauriejones** [comment]
Merged in and bumped up to 0.4.5
